spring:
  cloud:
    stream:
      bindings:
        testInput:
          destination: testInput
          binder: local_solace
          group: group
        myOutput:
          destination: anOutput
          binder: local_solace
        anotherOutput:
          destination: anotherOutput
          binder: local_solace
      binders:
        local_solace:
          type: solace
          environment:
            solace:
              java:
                host: 192.168.65.3
                msgVpn: default
                clientUsername: default
                clientPassword: default
