spring:
  cloud:
    stream:
      bindings:
        input:
          destination: myInput
          binder: solace
          group: test.group
        output:
          destination: myOutput
          binder: solace
  security:
    user:
      name: admin
      password: solace1
server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include:
        - bindings
solace:
  java:
    host: 192.168.65.3
    msgVpn: default
    clientUsername: default
    clientPassword: default
