spring:
  cloud:
    stream:
      bindings:
        input:
          destination: myInput
          binder: local_solace
          group: test.group
        output:
          destination: myOutput
          binder: local_solace
      binders:
        local_solace:
          type: solace
          environment:
            solace:
              java:
                host: 192.168.65.3
                msgVpn: default
                clientUsername: default
                clientPassword: default          
  security:
    user:
      name: admin
      password: solace1
server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include:
        - bindings
