spring:
  cloud:
    stream:
      bindings:
        someInput:
          destination: someInput
          binder: local_solace
          group: group
        lowOutput:
          destination: lowOutput
          binder: local_solace
        highOutput:
          destination: highOutput
          binder: local_solace
      binders:
        local_solace:
          type: solace
          environment:
            solace:
              java:
                host: 192.168.65.3
                msgVpn: default
                clientUsername: default
                clientPassword: default
